// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcQUS5c-vN0FUrddCuInxB634EWQEutAQ',
    appId: '1:535674134914:web:685f33b44f1cdf8b362f9b',
    messagingSenderId: '535674134914',
    projectId: 'loja-virtual-d64cf',
    authDomain: 'loja-virtual-d64cf.firebaseapp.com',
    databaseURL: 'https://loja-virtual-d64cf-default-rtdb.firebaseio.com',
    storageBucket: 'loja-virtual-d64cf.appspot.com',
    measurementId: 'G-P1793WF9S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW_6LvTJY4Js5cAxN0tPN6Prnfu23GLqI',
    appId: '1:535674134914:android:c283956010fc1dd1362f9b',
    messagingSenderId: '535674134914',
    projectId: 'loja-virtual-d64cf',
    databaseURL: 'https://loja-virtual-d64cf-default-rtdb.firebaseio.com',
    storageBucket: 'loja-virtual-d64cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfB-P1e5AaOX5DzGkKJkwahQCEuJiZ93U',
    appId: '1:535674134914:ios:94d765e5a72039c5362f9b',
    messagingSenderId: '535674134914',
    projectId: 'loja-virtual-d64cf',
    databaseURL: 'https://loja-virtual-d64cf-default-rtdb.firebaseio.com',
    storageBucket: 'loja-virtual-d64cf.appspot.com',
    iosClientId: '535674134914-hi0973ldq5fpvb6vpunagcciangomdvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.lojavirtual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfB-P1e5AaOX5DzGkKJkwahQCEuJiZ93U',
    appId: '1:535674134914:ios:94d765e5a72039c5362f9b',
    messagingSenderId: '535674134914',
    projectId: 'loja-virtual-d64cf',
    databaseURL: 'https://loja-virtual-d64cf-default-rtdb.firebaseio.com',
    storageBucket: 'loja-virtual-d64cf.appspot.com',
    iosClientId: '535674134914-hi0973ldq5fpvb6vpunagcciangomdvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.lojavirtual',
  );
}
